name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        go-version: [1.23.0] 

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build
        run: |
          mkdir -p release
          GOOS=${{ matrix.os == 'windows-latest' && 'windows' || (matrix.os == 'macos-latest' && 'darwin' || 'linux') }} GOARCH=amd64 go build -o release/ayah-sender cmd/ayah-sender-cli/main.go

      - name: Upload Release Assets
        uses: actions/upload-artifact@v3
        with:
          name: ayah-sender-${{ matrix.os }}
          path: release/ayah-sender
          
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}  # Corrected input parameter
          files: release/ayah-sender
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}